### PR TITLE
Intra cherche

### PR DESCRIPTION
**Pull request by IntraCherche**
The 4 methods I am suggesting to include provide the MapContainer with a way to retrieve the North East and South West boundaries of the displayed map. These methods have been implemented for iOS and Android only.

Related SO question is http://stackoverflow.com/questions/42096174/how-to-get-my-mapcontainer-bounding-box-in-codename-one/42106976?noredirect=1#comment71597619_42106976

Regards

### CODE REVIEW

**Comment by shannah** [comment]
I think we should just fix getCoordAtPosition then implement these methods in a cross-platform way, rather than introduce additional native methods.

A quick review of the code reveals that the way the simulator does it is consistent with the javadocs (x,y in component relative coords).  All other implementations are treating them as screen coordinates - which disagrees with javadocs.  Should be an easy fix.

**Comment by IntraCherche** [comment]
So I may have misunderstood the method goals. If I do :

/Coord NW = currentMap.getCoordAtPosition(0, 0);//
//        Point shouldBe00 = currentMap.getScreenCoordinate(NW);//
//        System.err.println("NW should be at 0 ; 0 => x = " + 
shouldBe00.getX() + " y = " + shouldBe00.getY());/

Then I get :

/NW should be at 0 ; 0 => x = -35 y = -673/

**Comment by codenameone** [comment]
I would do the opposite. I'd fix it to align with the devices which is what really matters...
We rely on MapComponent now but that's a dead end. Instead we should move to work based on the industry standard which is how Google works.

**Comment by shannah** [comment]
My point is that this behaviour is redundant.  it can be implemented using getCoordAtPosition() which does have native mapping and works on all platforms.  There is no reason to add additional native touch points.

**Comment by shannah** [comment]
@IntraCherche I replied to the SO thread here http://stackoverflow.com/a/42232943/2935174

**Comment by IntraCherche** [comment]
That fines me! You rock CN1 ;-)!

**Pull request closed without merging**
